#!/bin/bash
export EKLT_BATCH_SIZE=300
export EKLT_BLOCK_SIZE=3
export EKLT_DISPLACEMENT_PX=0.6
export EKLT_LK_WINDOW_SIZE=20
export EKLT_MAX_CORNERS=100
export EKLT_MAX_NUM_ITERATIONS=10
export EKLT_MIN_CORNERS=0
export EKLT_MIN_DISTANCE=10
export EKLT_NUM_PYRAMIDAL_LAYERS=3
export EKLT_PATCH_SIZE=25 
export EKLT_QUALITY_LEVEL=0.01
export EKLT_SCALE=4
export EKLT_TRACKING_QUALITY=0.6